#!/bin/bash

../../llvm-project/build/bin/clang++ -target arm64e-apple-darwin -fsanitize=dvipac -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -fno-ptrauth-intrinsics -fno-ptrauth-returns -fno-ptrauth-calls -fno-ptrauth-indirect-gotos -fno-ptrauth-auth-traps -g $1.cpp -o $1
